//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADGroup4L3C3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockManagment
    {
        public int StockManagementID { get; set; }
        public int StockID { get; set; }
        public string OperationType { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int UserAccountID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual UserAccounts UserAccounts { get; set; }
        public virtual UserAccounts UserAccounts1 { get; set; }
    }
}
